igrigorik/istlsfastyet.com

- .gitignore
- index.html
This moves a couple protocol-relative URLs over to HTTPS, adds the `forceSSL` flag for GA, and turns on [IP anonymization](https://support.google.com/analytics/answer/2763052?hl=en). 
I also moved the platform.twitter.com URL to `https://`, but worth noting that subsequent fetches by Twitter introspect the URL and default to `http://` anyway (though some of them have HSTS).
> Tighten up use of HTTPS locally, turn on IP anonymization for GA

- index.html
Hitch is brought to you by Varnish Software <https://github.com/varnish/hitch>
Hitch is a libev-based high performance SSL/TLS proxy, usually deployed for terminating HTTPS traffic in front of other origin servers.
Notable features:
* TLS1.0, TLS1.1 and TLS1.2 support
* SNI, with and without wildcard certificates.
* Support for HAproxy's PROXY protocol.
Hitch is open-source software, licensed under the 2-clause BSD license. It is maintained by Dag Haavi Finstad / Varnish Software.
> Adding Hitch (scalable TLS proxy by Varnish Software)

- index.html
It looks like https://*.appspot.com/ domains respond using HTTP/2.
> App Engine supports HTTP/2

- index.html
Features based on 1.5 (current stable), so linking to `golang.org/x/net/http2` for h2 support.
This is based on my understanding of the code (even though I only linked to the documentation), so @bradfitz and/or @agl should probably review.
> Add Golang to server list

- index.html
Hello,
This PR adds H2O to the list of servers.
I have set `Dynamic record sizing` column is set to `static`, regarding the fact that H2O hard-codes the TLS record size to be slightly among 1,400 bytes (see https://github.com/h2o/h2o/blob/v1.7.0/lib/common/socket.c#L375-L377).
Please let me know if you have any suggestions.  Thank you in advance.
> add H2O (h2o.examp1e.net)

- index.html
Hello Mr. Grigorik,
We have (finally) enabled Forward Secrecy on our edge servers. :confetti_ball: 
Proof: https://www.ssllabs.com/ssltest/analyze.html?d=code.jquery.com&hideResults=on
Other sites are in the process of being moved over to the new TLS config.
Next: Dynamic record sizing, then HTTP/2.
> Updated Forward Secrecy state for MaxCDN

- index.html
Fastly supports ALPN: https://www.ssllabs.com/ssltest/analyze.html?d=www.fastly.com&hideResults=on
> Updating index.html - Fastly supports ALPN.

- index.html
Hi Ilya,
I've added supported TLS and HTTP/2 features for Brocade virtual Traffic Manager to your table (disclaimer: I work on this product). Thanks for a great website + book.
Regards,
Jonathan.
> Add supported TLS and HTTP/2 features for Brocade virtual Traffic Manager

- index.html
Learned today from CCare @ Akamai. Advised it will be "enabled again in the future", but they have no ETA to share. :disappointed:
> Akamai is not currently supporting OCSP stapling

- index.html
Adjusting Faslty's entry for dynamic record sizing from "yes" to "dynamic" to match other providers in that column.  Sorry for not catching this in the initial request.
> Adjust Fastly dynamic record sizing nomenclature

- index.html
Another quick update - we now support HTTP/2
https://www.fastly.com/blog/announcing-limited-availability-http2
> Set HTTP/2 to yes for Fastly

- index.html
https://aws.amazon.com/about-aws/whats-new/2016/09/amazon-cloudfront-now-supports-http2/
> CloudFront supports HTTP/2 now

- index.html
Updates the CDN section of the page to add an AWS Application Load Balancer section and differentiate between the classic and application versions.
Also updates the section to include new updates made to the Application Load Balancer such as HTTP/2.
> Added AWS Application Load Balancer section

- index.html
Also update HTTP/2 link to point to the Go 1.6 release notes
Note that the link for dynamic record sizing points to the Go 1.7 release notes, which haven't been published yet, as Go 1.7 only just got its beta1. In the mean time, the draft release notes can be found at https://tip.golang.org/doc/go1.7#crypto/tls
I'd advise waiting for Go 1.7 to be released in a couple months before merging this PR. Thought I'd prepare it anyway, as soon as I saw the good news in the release notes.
BTW, didn't know whether to put a “yes” or “dynamic” in there.
> Golang 1.7 supports dynamic record sizing

- index.html
Hitch requires an h2c server such as Varnish 5.0 to handle the ALPN hint it provides and thus support H2 towards the client.
> Hitch w/ ALPN/NPN and HTTP/2 plaintext support

- index.html
Netlify uses ATS in the CDN pops, we provide all guarantees ATS provides out of the box.
I reorganized the list of PaaS to be alphabetically sorted too.
> Add Netlify to the list of PaaS

- index.html
Anchor was changed from crypto/tls to crypto_tls in golang/go@55559f1
> Fix link to Go 1.7 release notes wrt dynamic record sizing

- index.html
You may also want to set it to `feedback-based` or something to reflect the fact that H2O uses feedback from TCP/IP stack (CWND and latency) to decide the strategy.
> set TLS record sizing to H2O to `dynamic`

- index.html
H2O grew support for TLS1.3 in 2.2.0 by bundling an newer version of PicoTLS.
Linked to release notes since I couldn't find too specific info to tls 1.3 on the website. Will do another PR when upstream documentation gets updated.
> h2o: add support for 0-RTT TLS1.3

- index.html
As of version 1.13.0 (mainline) nginx now now supports TLSv1.3.
See: https://twitter.com/nginxorg/status/856896480497385473
> index.html: Add TLSv1.3 support to nginx

- index.html
Messages confirming the removal can be found [here](https://gitter.im/netlify/community?at=5a1f1fbf87680e6230af714c).
They hope to add it back in the future.
> Removed outdated Netlify support for OCSP Stapling

- index.html
Note that the old link seemed to refer to a different section, but that section is basically a glossary. So I changed it to one that actually describes the API.
> Fix Node.js ALPN/NPN link

- index.html
Referencing issue #170 KeyCDN added TLS 1.3 + 0-RTT support
> Add entry for KeyCDN TLS 1.3 + 0-RTT support

- index.html
Hi Ilya,
We've launched the latest TLS 1.3 a few weeks ago. Working on 0-RTT right now, it will be added by the end of October.
I'd also like to introduce our TLS checker made for a quick server or CDN check of its SSL/TLS protocols setup: https://www.cdn77.com/tls-test It's faster than other testing tools as it only goes for the protocol versions.
Have a great day,
Michal
> CDN77 with the latest TLS 1.3

- index.html
Hitch 1.5.0 adds support for TLS 1.3 (see: https://github.com/varnish/hitch/blob/master/CHANGES.rst#hitch-150-2018-12-17)
> Note Hitch supports TLS 1.3

- README.md
- index.html
Rewrote most links to use the https:// scheme
Nginx has added support for 0-RTT
> Link Updates and Nginx 0-RTT Support

- index.html
bud was deprecated and its repository was archived about two months ago: https://github.com/indutny/bud
This software is no longer being developed and should therefore be removed from the list.
> Remove bud from index.html

- index.html
This PR adds support for TLS 1.3 (RFC 8446) to F5 BIG-IP. TLS 1.3 support based on RFC 8446 was [added to F5 BIG-IP in version 14.1.0.1 and released on January 23rd, 2019](https://support.f5.com/kb/en-us/products/big-ip_ltm/releasenotes/product/relnote-bigip-14-1-0.html#rn_ltm-tmos_14101_new).
> Support for TLS 1.3 based on RFC8446 is added in F5 BIG-IP 14.1.0.1

- index.html
This PR adds support for TLS 1.3 (RFC 8446) to Go and Caddy. It replaces the previous PR #181.
> Add TLS 1.3 support to Go and Caddy

- index.html
Support for TLS 1.3 and TLS 1.3 0-RTT was added to nghttpx in v1.34.0: https://nghttp2.org/blog/2018/10/04/nghttp2-v1-34-0/
NetScaler was renamed to Citrix ADC and had support for TLS 1.3 added in September last year: https://www.citrix.com/blogs/2018/09/11/citrix-announces-adc-support-for-tls-1-3/
> Update name of NetScaler, add TLS 1.3 support to Citrix ADC and nghttpx and TLS 1.3 0-RTT support to nghttpx

- index.html
I also updated the HTTP/2 link to point to the nodejs.org docs about the built-in HTTP/2 server.
> Node now supports TLS 1.3!

- index.html
also updated documentation links.
> Akamai TLS 1.3 support is no longer beta.

- index.html
Updated Instart company name and latest information on what TLS features we support.
> New company name, OCSP and TLS 1.3 support

- index.html
StackPath now supports TLS 1.3:
```
$ openssl s_client -tls1_3 www.stackpath.com:443 | grep 'TLSv1.3'
depth=2 C = US, ST = New Jersey, L = Jersey City, O = The USERTRUST Network, CN = USERTrust RSA Certification Authority
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=1 C = GB, ST = Greater Manchester, L = Salford, O = Sectigo Limited, CN = Sectigo RSA Domain Validation Secure Server CA
verify return:1
depth=0 OU = Domain Control Validated, CN = www.stackpath.com
verify return:1
New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
```
> StackPath now supports TLS 1.3

- index.html
However, there isn't a dedicated documentation page about H2 support. We use the `alpn-protos` directive to configure H2 as shown in https://github.com/varnish/hitch/blob/master/docs/configuration.md#alpnnpn-support
My suggestion is to link to this page. You already referred to it in the ALPN section. If you don't like this, I can change it into `<td class="ok">yes</td>`
> H2 support in Hitch has been stable for years.

- index.html
Press release and video: https://www.fastly.com/blog/tls13-available
0-RTT may class as "Yes" rather than "warn". Fastly say:
> Fastly currently only supports 0-RTT between Fastly and requesting clients. We do not support 0-RTT between Fastly and your origin servers.
By default, Fastly only answers idempotent requests (GET and HEAD requests without query parameters) over 0-RTT. This helps protect customer applications from replay attacks.
Requests issued with 0-RTT will include an Early-Data:1 header per RFC 8470. This attribute can be queried and logged via VCL using req.http.early-data.
Closes #202
> Fastly supports TLS 1.3 and 0-RTT

- index.html
An email went out to customers in 2019 that TLSv1.3 to was supported and that it was being enabled for any customers that didn't requests specific protocols
Unfortunately I could not find public product specs or blog posting that denote Limelight's capabilities. Running an SSL labs tests against www.limelight.com: 
https://www.ssllabs.com/ssltest/analyze.html?d=llnw%2ddd.lldns.net&s=68.142.68.1
> Limelight supports TLSv1.3

- index.html
With the release of Windows Server 2022, IIS now finally supports TLS 1.3.
> Add TLS 1.3 support for IIS
