index.html

https://www.incapsula.com/blog/http2-is-here-what-you-need-to-know.html
https://http2.incapsula.com

Incapsula added HTTP/2 support

---

index.html

Update the mention of Let's Encrypt to remove the note that it was in beta.

Let's Encrypt is now generally available!

---

index.html

See Protocol Details section of
https://www.ssllabs.com/ssltest/analyze.html?d=verizondigitalmedia.com

EdgeCast supports ALPN

---

index.html

Quick update -- we now support dynamic record sizing at Fastly.

Fastly now supports dynamic record sizing.

---

index.html

F5 BIG-IP now supports Dynamic Record Sizing in v12.1.0, released 18.May.2016

Update Server table for F5 BIG-IP

---

index.html

Updated MaxCDN's HTTP/2 status to yes

---

index.html

https://client.cdn77.com/support/knowledgebase/general-faq/ssl-tech-specs

Added Dynamic record sizing ~ CDN77

---

index.html

Hello Ilya, 
I would be grateful if you can merge the TLS spec for ShimmerCat. Thanks in advance. 
./Alcides.

Add ShimmerCat TLS capabilities

---

index.html

Hi Ilya,
I'm from BelugaCDN.com and we'd like to add ourselves to your site.
Thanks and let me know if you have any questions,
-Adam

add BelugaCDN.com

---

index.html

Already enabled globally.
https://incapsula.zendesk.com/hc/en-us/articles/235148027-Incapsula-TLS-SSL-Tech-Specs

Incapsula added Dynamic Record Sizing

---

index.html

Incapsula added OCSP stapling

---

index.html

Updating HTTP/2 from No to Yes for EdgeCast Networks.

Adding HTTP/2 for EdgeCast Networks

---

index.html

https://www.cdn77.com/blog/cdn77-tls-1-3-supported/

CDN77 TLS 1.3 beta support

---

index.html

Akamai now supports OCSP stapling.

---

index.html

Hi all,
based on info from https://github.com/igrigorik/istlsfastyet.com/issues/145 I've added Caddy.
Cheers and have a nice weekend
midzer

added caddy

---

index.html

After testing it for some time, we just deployed 0-RTT globally.

CDN77 adds 0-RTT support

---

index.html

EdgeCast now supports TLS1.3

---

index.html

We currently support:
- Session identifiers
- Session tickets
- OCSP stapling
- ALPN
- Forward secrecy
- HTTP/2
- TLS 1.3
We don't support these right now:
- Dynamic record sizing
- TLS 1.3 0-RTT

Add Vercel Edge Network

---

index.html

Please add lighttpd to the server list.  Thank you.

please add lighttpd to the server list

---

index.html

Add TLS 1.3 support for Imperva Incapsula
